version: '3.7'

services:
  curator:
    build:
      context: extensions/curator/
    init: true
    volumes:
      - ./config/curator.yml:/.curator/curator.yml:ro,Z
      - ./config/delete_log_files_curator.yml:/.curator/delete_log_files_curator.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - yan
    depends_on:
      - elasticsearch
