---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster-neo
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true

# server.publicBaseUrl: https://my-elasticsearch-cluster.example.com

## Set the built-in users' passwords.
# Run the following command from the Elasticsearch directory:
# ./bin/elasticsearch-setup-passwords interactive
