using static System.Linq.Enumerable;

namespace YANLib.Core;

public static partial class YANUnmanaged
{
    /// <summary>
    /// Generates a random byte value within the specified minimum and maximum bounds.
    /// If the minimum or maximum values are invalid or unspecified, defaults to the minimum and maximum limits of a byte.
    /// If the minimum value is greater than the maximum, returns the default byte value.
    /// </summary>
    /// <param name="min">The minimum bound for the byte value. Can be <see langword="null"/>.</param>
    /// <param name="max">The maximum bound for the byte value. Can be <see langword="null"/>.</param>
    /// <returns>A randomly generated byte value within the specified bounds, or the default value of a byte if bounds are invalid.</returns>
    public static byte GenerateRandomByte(object? min = null, object? max = null)
    {
        var minValue = min.IsNull() ? byte.MinValue : min.To<byte>();
        var maxValue = max.IsNull() ? byte.MaxValue : max.To<byte>();

        return minValue > maxValue ? default : new Random().Next(minValue, maxValue).To<byte>();
    }

    /// <summary>
    /// Generates a collection of random byte values within specified minimum and maximum bounds, and of a specified size.
    /// If the minimum or maximum values are invalid or unspecified, uses the minimum and maximum limits of a byte.
    /// If the size is unspecified, defaults to a collection of size 0.
    /// </summary>
    /// <param name="min">The minimum bound for the byte values. Can be <see langword="null"/>.</param>
    /// <param name="max">The maximum bound for the byte values. Can be <see langword="null"/>.</param>
    /// <param name="size">The number of random byte values to generate. Can be <see langword="null"/>.</param>
    /// <returns>An enumerable collection of randomly generated byte values within the specified bounds and of the specified size.</returns>
    public static IEnumerable<byte> GenerateRandomBytes(object? min = null, object? max = null, object? size = null) => Range(0, size.To<uint>().To<int>()).Select(i => GenerateRandomByte(min, max));
}
