GET {{HostAddress}}/{{DeveloperType}}?pageNumber=1&pageSize=10
Authorization: Bearer {{Token}}

###
GET {{HostAddress}}/{{Developer}}?pageNumber=1&pageSize=10
Authorization: Bearer {{Token}}

###
GET {{HostAddress}}/{{Project}}?pageNumber=1&pageSize=10
Authorization: Bearer {{Token}}

###
GET {{HostAddress}}/{{DeveloperProject}}?pageNumber=1&pageSize=10
Authorization: Bearer {{Token}}

###